# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Each target defines cre-cli, account, and rpcs groups.
#
# Example custom target:
# my-target:
#   account:
#     workflow-owner-address: "0x123..."            # Optional: Owner wallet/MSIG address (used for --unsigned transactions)
#   rpcs:
#     - chain-name: ethereum-testnet-sepolia        # Required if your workflow interacts with this chain
#       url: "<select your own rpc url>"
#     - chain-name: ethereum-mainnet                # Required if your workflow interacts with this chain
#       url: "<select your own rpc url>"
#
# Experimental chains (automatically used by the simulator when present):
# Use this for chains not yet in official chain-selectors (e.g., hackathons, new chain integrations).
# In your workflow, reference the chain as evm:ChainSelector:<chain-id>@1.0.0
#
#   experimental-chains:
#     - chain-id: 12345                             # The numeric chain ID
#       rpc-url: "https://rpc.example.com"          # RPC endpoint URL
#       forwarder: "0x..."                          # Forwarder contract address on the chain

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://sepolia.gateway.tenderly.co/3ToZEWUfJV5n5KoTz1vaBG

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://sepolia.gateway.tenderly.co/3ToZEWUfJV5n5KoTz1vaBG
