# ==========================================================================
# AgentIndex Performance Tracker - CRE Workflow
# ==========================================================================
# Reads bonding curve state (supply, reserve, price, slope) on-chain,
# computes deterministic performance metrics via DON consensus,
# writes verified metrics to AgentMetrics, and adjusts bonding curve
# slopes based on computed performance.

# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "agentindex-tracker-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "agentindex-tracker-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""
